### ISSUE TITLE
How to account for wavelength differences in filtering cube?

### ISSUE THREAD

**Issue by trungtindinh** [a-rouxel/simca#2]
I have a hyperspectral cube as the input, but I vary the wavelength vectors for different simulations. I obtain two slightly different acquisitions as the output (which is expected), but the filtering cube exported in both cases are the same. My question is: should the difference in wavelengths be taken into account in the filtering cube? How does the simulator handle this difference? I assume that the simulator does take the difference into account, because I can see the difference between the two simulated acquisitions.

**Comment by a-rouxel** [comment]
Hello Tin,

The filtering cube characteristics  does not depend on the input scene. It depends ONLY on the system parameters that can be changed directly in the /simca/configs/cassi_system.yml file or through the GUI in the "Optical design" tab.

The idea there is that the number of spectral samples to consider will vary depending on the spectral dispersion of your system and the characteristics of your detector (more precisely : small pixels and high spectral dispersion => high number of spectral samples). Usually, you will want to consider a number of spectral bands that is higher than the one in your input scene. Also, you should consider having a number of spectral band large enough so that you have at least 2 spectral samples per pixel (ex : if you have a linear spectral dispersion, when using a grating for example, of 1mm and you consider detector pixels of 10um,  you should at set the number of spectral bands to 200). When you set this number of bands, as well as min and max wavelength, you define the filtering cube spectral sampling (linear interpolation between these min and max values).

That being said, the simulator indeed takes into account the hyperspectral scene wavelengths vector contained in the input .h5 file. To match the spectral sampling of the filtering cube, the input scene is interpolated according to the spectral sampling of this cube. So if you have 2 input scenes with different wavelength vectors, the INTERPOLATED SCENES WILL BE DIFFERENT. these interpolated input scenes are usually saved after an acquisition (cf. save_data_in_hdf5("interpolated_scene",cassi_system.interpolated_scene, cassi_system.result_directory) in multiple_acquisitions_script.py) to be able to evaluate your image processing results (particularly useful for reconstruction algorithms).

**Comment by trungtindinh** [comment]
Thank you for the explanation ;)
